#!/usr/bin/env python3
import argparse
import csv
import json
import os
import re
import subprocess
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

import torch

from evaluate_rmot import evaluate


PROJECT_ROOT = Path(__file__).resolve().parents[1]
SETTINGS = (
    {"name": "K64", "K": 64, "theta": 0.35, "delta": 0.45},
    {"name": "default", "K": 96, "theta": 0.35, "delta": 0.45},
    {"name": "K128", "K": 128, "theta": 0.35, "delta": 0.45},
    {"name": "theta025", "K": 96, "theta": 0.25, "delta": 0.45},
    {"name": "theta045", "K": 96, "theta": 0.45, "delta": 0.45},
    {"name": "delta035", "K": 96, "theta": 0.35, "delta": 0.35},
    {"name": "delta055", "K": 96, "theta": 0.35, "delta": 0.55},
)


def checkpoint_tag(checkpoint):
    numbers = re.findall(r"\d+", checkpoint.stem)
    return numbers[-1] if numbers else checkpoint.stem


def validate_checkpoint(checkpoint_path):
    try:
        checkpoint = torch.load(
            checkpoint_path, map_location="cpu", weights_only=False
        )
    except TypeError:
        checkpoint = torch.load(checkpoint_path, map_location="cpu")
    model_state = checkpoint.get("model", checkpoint)
    required = (
        "state_init_query.weight",
        "transformer.decoder.layers.0.geometry_gate.0.weight",
        "transformer.decoder.layers.0.quality_head.weight",
    )
    missing = [fragment for fragment in required if not any(fragment in key for key in model_state)]
    if missing:
        raise ValueError(
            "checkpoint predates the paper-aligned DriftGuard implementation; "
            f"missing parameters: {', '.join(missing)}"
        )


def inference_command(args, setting, run_dir):
    return [
        "bash",
        str(args.test_script),
        "--evidence_topk",
        str(setting["K"]),
        "--evidence_score_thresh",
        str(setting["theta"]),
        "--state_update_thresh",
        str(setting["delta"]),
        *args.extra_args,
    ]


def run_inference(args, setting, gpu):
    run_dir = args.output_root / setting["name"]
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "setting.json").write_text(
        json.dumps({**setting, "gpu": str(gpu)}, indent=2) + "\n"
    )
    log_path = run_dir / "inference.log"
    env = os.environ.copy()
    env.update(
        {
            "PROJECT_ROOT": str(PROJECT_ROOT),
            "DATA_ROOT": str(args.data_root),
            "CHECKPOINT": str(args.checkpoint),
            "TEXT_ENCODER_PATH": args.text_encoder_path,
            "OUTPUT_DIR": str(run_dir),
            "CUDA_VISIBLE_DEVICES": str(gpu),
        }
    )
    with log_path.open("w") as log_handle:
        subprocess.run(
            inference_command(args, setting, run_dir),
            cwd=PROJECT_ROOT,
            env=env,
            stdout=log_handle,
            stderr=subprocess.STDOUT,
            check=True,
        )
    return setting["name"]


def write_summaries(output_root, rows):
    csv_path = output_root / "sensitivity.csv"
    with csv_path.open("w", newline="") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=("Setting", "K", "theta", "delta", "HOTA", "AssA", "IDSW"),
        )
        writer.writeheader()
        writer.writerows(rows)

    tex_lines = [
        "% Generated by tools/run_sensitivity.py",
        "Setting & $K$ & $\\theta_{ev}$ & $\\delta_g$ & HOTA & AssA & IDSW \\\\",
        "\\midrule",
    ]
    for row in rows:
        tex_lines.append(
            "{Setting} & {K} & {theta:.2f} & {delta:.2f} & "
            "{HOTA:.2f} & {AssA:.2f} & {IDSW} \\\\".format(**row)
        )
    (output_root / "sensitivity_rows.tex").write_text("\n".join(tex_lines) + "\n")
    (output_root / "sensitivity.json").write_text(
        json.dumps(rows, indent=2) + "\n"
    )


def main():
    parser = argparse.ArgumentParser(
        description="Run the seven one-at-a-time DriftGuard sensitivity settings."
    )
    parser.add_argument("--data-root", required=True, type=Path)
    parser.add_argument("--checkpoint", required=True, type=Path)
    parser.add_argument("--text-encoder-path", required=True)
    parser.add_argument(
        "--output-root", type=Path,
        default=PROJECT_ROOT / "exps" / "driftguard_sensitivity_v2"
    )
    parser.add_argument(
        "--test-script", type=Path,
        default=PROJECT_ROOT / "configs" / "dkgtrack_rmot_test.sh"
    )
    parser.add_argument("--gpus", nargs="+", default=["0"])
    parser.add_argument("--jobs", type=int, default=1)
    parser.add_argument("--skip-inference", action="store_true")
    parser.add_argument("--extra-args", nargs=argparse.REMAINDER, default=[])
    args = parser.parse_args()

    if not args.skip_inference:
        if not args.data_root.exists():
            raise FileNotFoundError(args.data_root)
        if not args.checkpoint.exists():
            raise FileNotFoundError(args.checkpoint)
        validate_checkpoint(args.checkpoint)
        workers = max(1, min(args.jobs, len(args.gpus), len(SETTINGS)))
        with ThreadPoolExecutor(max_workers=workers) as executor:
            futures = {
                executor.submit(
                    run_inference, args, setting, args.gpus[index % len(args.gpus)]
                ): setting["name"]
                for index, setting in enumerate(SETTINGS)
            }
            for future in as_completed(futures):
                name = futures[future]
                future.result()
                print(f"completed inference: {name}", flush=True)

    tag = checkpoint_tag(args.checkpoint)
    rows = []
    for setting in SETTINGS:
        run_dir = args.output_root / setting["name"]
        results_root = run_dir / f"results_epoch{tag}"
        metrics_path = run_dir / "metrics.json"
        metrics = evaluate(results_root)
        metrics_path.write_text(json.dumps(metrics, indent=2, sort_keys=True) + "\n")
        rows.append(
            {
                "Setting": setting["name"],
                "K": setting["K"],
                "theta": setting["theta"],
                "delta": setting["delta"],
                "HOTA": round(metrics["HOTA"], 2),
                "AssA": round(metrics["AssA"], 2),
                "IDSW": metrics["IDSW"],
            }
        )

    args.output_root.mkdir(parents=True, exist_ok=True)
    write_summaries(args.output_root, rows)
    print(json.dumps(rows, indent=2))


if __name__ == "__main__":
    main()
